/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.Database;
import entidade.pessoa.Funcionario;
import exceção.DataInvalidaException;
import exceção.LoginException;
import exceção.PessoaExistenteException;
import exceção.PessoaInexistenteException;
import fachada.Fachada;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class Login extends javax.swing.JFrame {

    Fachada fachada;
    
    public Login(Fachada fachada) throws PessoaExistenteException, DataInvalidaException{
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(1060,740);
        this.inicializar();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entryLogin = new javax.swing.JTextField();
        entrySenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("LOGIN:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 300, 90, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("SENHA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 370, 92, 20);

        entryLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryLoginActionPerformed(evt);
            }
        });
        getContentPane().add(entryLogin);
        entryLogin.setBounds(440, 300, 260, 30);

        entrySenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrySenhaActionPerformed(evt);
            }
        });
        getContentPane().add(entrySenha);
        entrySenha.setBounds(440, 370, 260, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 430, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1043, 705);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrySenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrySenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySenhaActionPerformed

    private void entryLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpf = entryLogin.getText();
        String senha = entrySenha.getText();
        if(cpf.equals("") || senha.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            try{
               Funcionario f = fachada.login(cpf, senha);
               if(f.getGerente()){
                   TelaGerente tg = new TelaGerente(fachada);
                   tg.setLocationRelativeTo(null);
                   tg.setVisible(true);
                   tg.setResizable(false);
                   this.dispose();
               } 
               else if(!f.getGerente()){
                  TelaFuncionário tg = new TelaFuncionário(fachada);
                  tg.setLocationRelativeTo(null);
                  tg.setVisible(true);
                  tg.setResizable(false);
                  this.dispose();
               }
            } catch (PessoaInexistenteException ex) {
                JOptionPane.showMessageDialog(null, "Funcionário não cadastrado!");
            } catch (LoginException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public void inicializar() throws PessoaExistenteException, DataInvalidaException{
        Date data = new Date();
       
    }
    /*
    public static void main(String args[]) throws PessoaExistenteException, DataInvalidaException{
        Fachada f = Fachada.getInstancia();
        Database banco = new Database();
        banco.iniciarBanco();
        final Login login = new Login(f);
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
               login.setVisible(true);
               login.setLocationRelativeTo(null);
               login.setResizable(false);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entryLogin;
    private javax.swing.JPasswordField entrySenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
