/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exceção.QuartoExistenteException;
import fachada.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaCadastroQuarto extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaCadastroQuarto(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        entryNumero = new javax.swing.JTextField();
        entryCapacidade = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        checkBoxGerente2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        entryDiaria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Número:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 210, 100, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Capacidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 250, 120, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 500, 90, 30);

        entryNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(entryNumero);
        entryNumero.setBounds(170, 210, 180, 30);

        entryCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCapacidadeActionPerformed(evt);
            }
        });
        getContentPane().add(entryCapacidade);
        entryCapacidade.setBounds(170, 250, 180, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 510, 90, 30);

        checkBoxGerente2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBoxGerente2.setText("Premium");
        checkBoxGerente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGerente2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxGerente2);
        checkBoxGerente2.setBounds(230, 360, 180, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Diaria: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 290, 80, 30);
        getContentPane().add(entryDiaria);
        entryDiaria.setBounds(170, 290, 180, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNumeroActionPerformed

    private void entryCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCapacidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numero = entryNumero.getText();
        String diaria = entryDiaria.getText();
        String c = entryCapacidade.getText();
        boolean premium = checkBoxGerente2.isSelected();
        if(numero.equals("") || c.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
           try{            
                int capacidade = Integer.parseInt(c);
                double diariaV = Double.parseDouble(diaria);
                
                fachada.adicionarQuarto(numero, capacidade, diariaV, false, 0.00, premium);
                JOptionPane.showMessageDialog(null, "Quarto Cadastrado!");
                this.dispose();
                
            } catch (QuartoExistenteException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Capacidade e diária recebem números!");
            } 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkBoxGerente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGerente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxGerente2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox checkBoxGerente2;
    private javax.swing.JTextField entryCapacidade;
    private javax.swing.JTextField entryDiaria;
    private javax.swing.JTextField entryNumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
