/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exceção.CheckInNaoRealizadoException;
import exceção.ItemInexistenteException;
import exceção.QuartoInexistenteException;
import fachada.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaRoomService extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaRoomService(Fachada fachada) {
        initComponents();
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        atualizarAreaTexto();
        setSize(1060,740);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entryNumeroQuarto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxHospede = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        entryCodigo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 260, 450, 270);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quarto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 380, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Opções:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 220, 80, 30);
        getContentPane().add(entryNumeroQuarto);
        entryNumeroQuarto.setBounds(300, 380, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(950, 530, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 460, 50, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Opções:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 77, 30);

        ComboBoxHospede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "Cadastrar", "Atualizar", "Remover" }));
        ComboBoxHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxHospede);
        ComboBoxHospede.setBounds(30, 270, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Código:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 420, 90, 30);
        getContentPane().add(entryCodigo);
        entryCodigo.setBounds(300, 420, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(830, 230, 90, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1043, 705);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String numeroQuarto = entryNumeroQuarto.getText();
        String cod = entryCodigo.getText();
        try{
            int codigo = Integer.parseInt(cod);
            fachada.solicitarServicoQuarto(numeroQuarto, codigo);
            JOptionPane.showMessageDialog(null, "Pedido Realizado!");
            entryNumeroQuarto.setText("");
            entryCodigo.setText("");
        }
        catch(QuartoInexistenteException | ItemInexistenteException | CheckInNaoRealizadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Digite um preço válido!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ComboBoxHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxHospedeActionPerformed
        Object x = ComboBoxHospede.getSelectedItem();
        switch (x.toString()) {
            case "Cadastrar":
            {
                TelaCadastroRoomService h = new TelaCadastroRoomService(fachada);
                h.setVisible(true);
                break;
            }
            case "Remover":
            {
                TelaRemoverRoomService h = new TelaRemoverRoomService(fachada);
                h.setVisible(true);
                break;
            }

            case "Atualizar":{
                TelaAttRoomService h = new TelaAttRoomService(fachada);
                h.setVisible(true);
                break;
            }
            default:
            break;
        }
    }//GEN-LAST:event_ComboBoxHospedeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.atualizarAreaTexto();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void atualizarAreaTexto(){
        String mensagem = fachada.opções();
        this.areaTexto.setText(mensagem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxHospede;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JTextField entryCodigo;
    private javax.swing.JTextField entryNumeroQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
