/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exceção.DataInvalidaException;
import exceção.PessoaExistenteException;
import fachada.Fachada;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elyson
 */
public class TelaCadastroFuncionário extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaCadastroFuncionário(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        entryNome = new javax.swing.JTextField();
        entrySenha = new javax.swing.JTextField();
        entryData = new javax.swing.JFormattedTextField();
        entrySalario = new javax.swing.JTextField();
        checkBoxGerente = new javax.swing.JCheckBox();
        entryCPF = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 200, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 240, 50, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data de Cadastro:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 290, 180, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Senha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 380, 70, 22);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Salario: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 330, 90, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 530, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 530, 100, 30);

        entryNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNomeActionPerformed(evt);
            }
        });
        getContentPane().add(entryNome);
        entryNome.setBounds(210, 200, 170, 30);

        entrySenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrySenhaActionPerformed(evt);
            }
        });
        getContentPane().add(entrySenha);
        entrySenha.setBounds(210, 370, 170, 30);

        try {
            entryData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(entryData);
        entryData.setBounds(210, 290, 170, 30);
        getContentPane().add(entrySalario);
        entrySalario.setBounds(210, 330, 170, 30);

        checkBoxGerente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBoxGerente.setText("Gerente");
        checkBoxGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxGerente);
        checkBoxGerente.setBounds(230, 440, 120, 30);

        try {
            entryCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        entryCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCPFActionPerformed(evt);
            }
        });
        getContentPane().add(entryCPF);
        entryCPF.setBounds(210, 240, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = entryNome.getText();
        String cpf = entryCPF.getText();
        String data = entryData.getText();
        String salario = entrySalario.getText();
        String senha = entrySenha.getText();
        boolean gerente = checkBoxGerente.isSelected();
        if(nome.equals("") || cpf.equals("   .   .   -  ") || data.equals("  /  /    ") || senha.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            try{
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date d = formato.parse(data);
                double salarioF = Double.parseDouble(salario);
                fachada.adicionarFuncionario(cpf, nome,gerente, senha, d,salarioF);
                JOptionPane.showMessageDialog(null, "Funcionário Cadastrado!");
                this.dispose();
            } catch (PessoaExistenteException | DataInvalidaException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            catch(ParseException ex){
                JOptionPane.showMessageDialog(null, "Digite a data no formato dd/MM/yyyy");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void entryNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNomeActionPerformed

    private void entrySenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrySenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySenhaActionPerformed

    private void checkBoxGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxGerenteActionPerformed

    private void entryCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxGerente;
    private javax.swing.JFormattedTextField entryCPF;
    private javax.swing.JFormattedTextField entryData;
    private javax.swing.JTextField entryNome;
    private javax.swing.JTextField entrySalario;
    private javax.swing.JTextField entrySenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
