/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entidade.quarto.Quarto;
import exceção.QuartoExistenteException;
import exceção.QuartoInexistenteException;
import fachada.Fachada;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaAttQuarto extends javax.swing.JFrame {
    
    Fachada fachada;
    
    public TelaAttQuarto(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        entryNumeroAtual = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        checkBoxGerente2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        entryTipo4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 510, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Número Atual:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 240, 160, 22);

        entryNumeroAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNumeroAtualActionPerformed(evt);
            }
        });
        getContentPane().add(entryNumeroAtual);
        entryNumeroAtual.setBounds(210, 240, 180, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 520, 90, 30);

        checkBoxGerente2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBoxGerente2.setText("Premium");
        checkBoxGerente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGerente2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxGerente2);
        checkBoxGerente2.setBounds(210, 280, 210, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 482, 595);

        entryTipo4.setText("Tipo 3");
        getContentPane().add(entryTipo4);
        entryTipo4.setBounds(300, 390, 60, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryNumeroAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNumeroAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNumeroAtualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numeroAtual = entryNumeroAtual.getText();
       
        boolean premium = checkBoxGerente2.isSelected();
        if(numeroAtual.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            try{
                
                Quarto q = fachada.buscarQuarto(numeroAtual);
                fachada.atualizarQuarto(q, premium);
                
                JOptionPane.showMessageDialog(null, "Quarto Atualizado!");
                this.dispose(); 
                
                      
            
            }catch (QuartoInexistenteException | QuartoExistenteException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkBoxGerente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGerente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxGerente2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxGerente2;
    private javax.swing.JTextField entryNumeroAtual;
    private javax.swing.JRadioButton entryTipo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
