package gui;

import exceção.CheckInRealizadoException;
import exceção.DataIndisponivelException;
import exceção.DataInvalidaException;
import exceção.PessoaInexistenteException;
import exceção.QuartoInexistenteException;
import exceção.ReservaExistenteException;
import exceção.ReservaInexistenteException;
import fachada.Fachada;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Gabrielle Amorim
 */
public class TelaCheckIn extends javax.swing.JFrame {

   Fachada fachada;
   
    public TelaCheckIn(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entryCodigoReserva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entryCpf = new javax.swing.JFormattedTextField();
        entryDC = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        entryDS = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        entryNumeroQuarto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Código da Reserva:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 191, 22);

        entryCodigoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCodigoReservaActionPerformed(evt);
            }
        });
        getContentPane().add(entryCodigoReserva);
        entryCodigoReserva.setBounds(210, 240, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 240, 60, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 310, 480, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 350, 50, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Data de Chegada:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 380, 180, 22);

        try {
            entryCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        entryCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCpfActionPerformed(evt);
            }
        });
        getContentPane().add(entryCpf);
        entryCpf.setBounds(260, 350, 170, 30);

        try {
            entryDC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(entryDC);
        entryDC.setBounds(260, 390, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data de Saída:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 420, 150, 22);

        try {
            entryDS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(entryDS);
        entryDS.setBounds(260, 430, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Número do Quarto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 470, 190, 22);

        entryNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNumeroQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(entryNumeroQuarto);
        entryNumeroQuarto.setBounds(260, 470, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 520, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(360, 520, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryCodigoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCodigoReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCodigoReservaActionPerformed

    private void entryCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCpfActionPerformed

    private void entryNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNumeroQuartoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String c = entryCodigoReserva.getText();
        if(c.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo código!");
        }
        else{
            try{  
            int codigo = Integer.parseInt(c);
            fachada.checkIn(codigo);
            JOptionPane.showMessageDialog(null, "Check-In Realizado!");
            this.dispose();
        }catch (ReservaInexistenteException | CheckInRealizadoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Informe um código válido! \n Ex: 10");
          }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cpf = entryCpf.getText();
        String dc = entryDC.getText();
        String ds = entryDS.getText();
        String numeroQuarto = entryNumeroQuarto.getText();
        if(cpf.equals("") || dc.equals("") || ds.equals("") || numeroQuarto.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
           try{           
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataChegada = formato.parse(dc);
            Date dataSaida = formato.parse(ds);
            double x = fachada.checkIn(dataChegada, dataSaida, numeroQuarto, cpf);
            JOptionPane.showMessageDialog(null, "Check-In Realizado!\n Total:R$ " + x);
            this.dispose();
            } catch (ParseException ex) {
               JOptionPane.showMessageDialog(null, "Digite a data no formato dd/MM/yyyy");
            } catch (ReservaInexistenteException | PessoaInexistenteException | ReservaExistenteException | QuartoInexistenteException | DataIndisponivelException | DataInvalidaException | CheckInRealizadoException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
              }
           }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entryCodigoReserva;
    private javax.swing.JFormattedTextField entryCpf;
    private javax.swing.JFormattedTextField entryDC;
    private javax.swing.JFormattedTextField entryDS;
    private javax.swing.JTextField entryNumeroQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
