package gui;

import fachada.Fachada;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import exceção.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaCadastroReserva extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaCadastroReserva(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InfoNumeroQuarto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InfoDataSaida = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        InfoDataChegada = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        InfoCPF = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 240, 44, 22);

        InfoNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoNumeroQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(InfoNumeroQuarto);
        InfoNumeroQuarto.setBounds(230, 390, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Data de Saída:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 340, 150, 22);

        try {
            InfoDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(InfoDataSaida);
        InfoDataSaida.setBounds(230, 340, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Data de Chegada:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 290, 190, 22);

        try {
            InfoDataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(InfoDataChegada);
        InfoDataChegada.setBounds(230, 290, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Número do Quarto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 390, 190, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 450, 90, 30);

        try {
            InfoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        InfoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCPFActionPerformed(evt);
            }
        });
        getContentPane().add(InfoCPF);
        InfoCPF.setBounds(230, 240, 170, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 500, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoNumeroQuartoActionPerformed

    private void InfoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoCPFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpf = this.InfoCPF.getText();
        String data1 = this.InfoDataChegada.getText();
        String data2 = this.InfoDataSaida.getText();
        String numeroQuarto = this.InfoNumeroQuarto.getText();
        if(cpf.equals("") || data1.equals("") || data2.equals("") || numeroQuarto.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
           try{            
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataChegada = formato.parse(data1);
                Date dataSaida = formato.parse(data2);
                double x = fachada.reservarQuarto(dataChegada, dataSaida, cpf, numeroQuarto);
                JOptionPane.showMessageDialog(null, "Reserva Cadastrada!\n Total:R$ " + x);
                this.dispose();
            }
            catch(PessoaInexistenteException | ReservaExistenteException | QuartoInexistenteException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
           catch(DataInvalidaException | DataIndisponivelException e){
               InfoDataChegada.setText("");
               InfoDataSaida.setText("");
               JOptionPane.showMessageDialog(null, e.getMessage());
           }
            catch(ParseException ex){
                JOptionPane.showMessageDialog(null, "Digite a data no formato dd/MM/yyyy");
            }  catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Digite uma quantidade válida!");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField InfoCPF;
    private javax.swing.JFormattedTextField InfoDataChegada;
    private javax.swing.JFormattedTextField InfoDataSaida;
    private javax.swing.JTextField InfoNumeroQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
