/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exceção.CheckInRealizadoException;
import exceção.QuartoInexistenteException;
import fachada.Fachada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaCheckOut extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaCheckOut(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.atualizarAreaTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        entryNumeroQuarto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Número do Quarto:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 200, 20);

        entryNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNumeroQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(entryNumeroQuarto);
        entryNumeroQuarto.setBounds(200, 260, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 260, 80, 30);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 310, 440, 110);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Realizar Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 490, 160, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 490, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNumeroQuartoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numeroQuarto = entryNumeroQuarto.getText();
        if(numeroQuarto.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo número do quarto!");
        }
        else{
          try {      
            fachada.checkOut(numeroQuarto);
            JOptionPane.showMessageDialog(null, "Check-Out Realizado!");
            this.dispose();
            } catch (QuartoInexistenteException | CheckInRealizadoException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numeroQuarto = entryNumeroQuarto.getText();
        if(numeroQuarto.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo número do quarto!");
        }
        else{
           try{           
            String mensagem = fachada.infoCheckOut(numeroQuarto);
            this.areaTexto.setText(mensagem);
            } catch (QuartoInexistenteException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
           catch(Exception e){
               JOptionPane.showMessageDialog(null, "Não foi realizado check-in nesse quarto!");
           }
        }        
    }//GEN-LAST:event_jButton2ActionPerformed
    private void atualizarAreaTexto(){
        try{
           String numeroQuarto = entryNumeroQuarto.getText();
           if(!numeroQuarto.equals("")){
                String mensagem = fachada.infoCheckOut(numeroQuarto);
                this.areaTexto.setText(mensagem);
            } 
        }
        catch (QuartoInexistenteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
        
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JTextField entryNumeroQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
