/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entidade.pessoa.Hospede;
import exceção.DataInvalidaException;
import exceção.PessoaExistenteException;
import fachada.Fachada;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielle Amorim
 */
public class TelaCadastroHospede extends javax.swing.JFrame {

    Fachada fachada;    
    
    public TelaCadastroHospede(Fachada fachada){
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        //atualizarCampoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InfoCpfCadHospede = new javax.swing.JFormattedTextField();
        entryTelefone = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        entryNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 320, 110, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 280, 44, 22);

        try {
            InfoCpfCadHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        InfoCpfCadHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCpfCadHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(InfoCpfCadHospede);
        InfoCpfCadHospede.setBounds(250, 280, 170, 30);

        try {
            entryTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(entryTelefone);
        entryTelefone.setBounds(240, 320, 190, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 520, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 520, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 230, 90, 22);

        entryNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNomeActionPerformed(evt);
            }
        });
        getContentPane().add(entryNome);
        entryNome.setBounds(250, 230, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoCpfCadHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCpfCadHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoCpfCadHospedeActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = entryNome.getText();
        String cpf = InfoCpfCadHospede.getText();
        String telefone = entryTelefone.getText();
        double debito = 0;
        if(nome.equals("") || cpf.equals("   .   .   -  ") || telefone.equals("(  )9.    -    ")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            try {
            Hospede h = new Hospede(cpf, nome, telefone, debito);
            fachada.adicionarHospede(h.getCpf(),h.getNome(),h.getTelefone(),h.getDebito());
            JOptionPane.showMessageDialog(null, "Hóspede Cadastrado!");
            this.dispose();
            } 
            catch(PessoaExistenteException e){
                InfoCpfCadHospede.setText("");
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (DataInvalidaException ex) {
                Logger.getLogger(TelaCadastroHospede.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void entryNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField InfoCpfCadHospede;
    private javax.swing.JTextField entryNome;
    private javax.swing.JFormattedTextField entryTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
