/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import exceção.DataInvalidaException;
import exceção.PessoaExistenteException;
import fachada.Fachada;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Elyson
 */
public class TelaGerente extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaGerente(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(1060,740);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ComboBoxHospede = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxQuartos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBoxReservas = new javax.swing.JComboBox<>();
        botãoCheckIn = new javax.swing.JButton();
        botaoCheckOut = new javax.swing.JButton();
        botaoServicoQuarto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFuncionarios = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Funcionários");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 260, 80, 15);

        ComboBoxHospede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "Cadastrar", "Atualizar", "Remover", "Listar" }));
        ComboBoxHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxHospede);
        ComboBoxHospede.setBounds(90, 240, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quartos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 300, 70, 15);

        comboBoxQuartos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------", "Cadastrar", "Atualizar Quarto", "Atualizar Categoria", "Remover", "Disponíveis", "Ocupados" }));
        comboBoxQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuartosActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxQuartos);
        comboBoxQuartos.setBounds(90, 320, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reservas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 380, 70, 15);

        comboBoxReservas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------", "Cadastrar", "Atualizar", "Remover", "Listar" }));
        comboBoxReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxReservasActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxReservas);
        comboBoxReservas.setBounds(90, 400, 200, 30);

        botãoCheckIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botãoCheckIn.setText("Check-In");
        botãoCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoCheckInActionPerformed(evt);
            }
        });
        getContentPane().add(botãoCheckIn);
        botãoCheckIn.setBounds(420, 260, 160, 40);

        botaoCheckOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoCheckOut.setText("Check-Out");
        botaoCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCheckOut);
        botaoCheckOut.setBounds(420, 320, 160, 40);

        botaoServicoQuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoServicoQuarto.setText("Serviço de Quarto");
        botaoServicoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicoQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoServicoQuarto);
        botaoServicoQuarto.setBounds(420, 380, 160, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(950, 520, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Hóspedes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 220, 80, 15);

        jComboBoxFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "Cadastrar", "Atualizar", "Remover", "Listar" }));
        jComboBoxFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFuncionarios);
        jComboBoxFuncionarios.setBounds(750, 280, 200, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Ficha Hóspedes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(890, 100, 150, 30);

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem1.png"))); // NOI18N
        getContentPane().add(jLabel);
        jLabel.setBounds(60, -10, 1043, 705);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxHospedeActionPerformed
        Object x = ComboBoxHospede.getSelectedItem();
        switch (x.toString()) {
            case "Cadastrar":
            {
                TelaCadastroHospede hospede = new TelaCadastroHospede(fachada);
                hospede.setVisible(true);
                break;
            }
            case "Remover":
            {
                TelaRemoverHospede hospede = new TelaRemoverHospede(fachada);
                hospede.setVisible(true);
                break;
            }

            case "Atualizar":{
                TelaAttHospede hospede = new TelaAttHospede(fachada);
                hospede.setVisible(true);
                break;
            }

            case "Listar":
            {
                TelaListarHospedes hospede = new TelaListarHospedes(fachada);
                hospede.setVisible(true);
                break;
            }
            default:
            break;
        }
    }//GEN-LAST:event_ComboBoxHospedeActionPerformed

    private void comboBoxQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuartosActionPerformed
        // TODO add your handling code here:
        Object x = comboBoxQuartos.getSelectedItem();
        switch (x.toString()) {
            case "Cadastrar":
            {
                TelaCadastroQuarto Quarto = new TelaCadastroQuarto(fachada);
                Quarto.setVisible(true);
                break;
            }
            case "Remover":
            {
                TelaRemoverQuarto Quarto = new TelaRemoverQuarto(fachada);
                Quarto.setVisible(true);
                break;
            }
            case "Atualizar Quarto":{
                TelaAttQuarto Quarto = new TelaAttQuarto(fachada);
                Quarto.setVisible(true);
                break;
            }
            
          
            case "Disponíveis":
            {
                TelaListarQuartos Quarto = new TelaListarQuartos(fachada);
                Quarto.setVisible(true);
                break;
            }
            case "Ocupados":
            {
                TelaListarQuartosOcupados Quarto = new TelaListarQuartosOcupados(fachada);
                Quarto.setVisible(true);
                break;
            }
            default:
            break;
        }

    }//GEN-LAST:event_comboBoxQuartosActionPerformed

    private void comboBoxReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxReservasActionPerformed
        // TODO add your handling code here:
        Object x = comboBoxReservas.getSelectedItem();
        switch (x.toString()) {
            case "Cadastrar":
            {
                TelaCadastroReserva Reserva = new TelaCadastroReserva(fachada);
                Reserva.setVisible(true);
                break;
            }
            case "Remover":
            {
                TelaRemoverReserva Reserva = new TelaRemoverReserva(fachada);
                Reserva.setVisible(true);
                break;
            }
            

            case "Listar":
            {
                TelaListarReservas Reserva = new TelaListarReservas(fachada);
                Reserva.setVisible(true);

                break;
            }
            default:
            break;
        }

    }//GEN-LAST:event_comboBoxReservasActionPerformed

    private void botãoCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoCheckInActionPerformed
        TelaCheckIn tela = new TelaCheckIn(fachada);
        tela.setVisible(true);

    }//GEN-LAST:event_botãoCheckInActionPerformed

    private void botaoCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCheckOutActionPerformed
        TelaCheckOut tela = new TelaCheckOut(fachada);
        tela.setVisible(true);
    }//GEN-LAST:event_botaoCheckOutActionPerformed

    private void botaoServicoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicoQuartoActionPerformed
        TelaRoomService tela;
        tela = new TelaRoomService(fachada);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        tela.setResizable(false);
    }//GEN-LAST:event_botaoServicoQuartoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login login;
        try {
            login = new Login(fachada);
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            login.setResizable(false);
            this.dispose();
        } catch (PessoaExistenteException | DataInvalidaException ex) {
            Logger.getLogger(TelaFuncionário.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionariosActionPerformed
        // TODO add your handling code here:
        Object x = jComboBoxFuncionarios.getSelectedItem();
        switch (x.toString()) {
            case "Cadastrar":
            {
                TelaCadastroFuncionário Reserva = new TelaCadastroFuncionário(fachada);
                Reserva.setVisible(true);
                break;
            }
            case "Remover":
            {
                TelaRemoverFuncionário Reserva = new TelaRemoverFuncionário(fachada);
                Reserva.setVisible(true);
                break;
            }
            case "Atualizar":{
                TelaAttFuncionário Reserva = new TelaAttFuncionário(fachada);
                Reserva.setVisible(true);
                break;
            }
            case "Listar":
            {
                TelaListarFuncionário Reserva = new TelaListarFuncionário(fachada);
                Reserva.setVisible(true);

                break;
            }
            default:
            break;
        }
    }//GEN-LAST:event_jComboBoxFuncionariosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaFichaHospede tela = new TelaFichaHospede(fachada);
        tela.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxHospede;
    private javax.swing.JButton botaoCheckOut;
    private javax.swing.JButton botaoServicoQuarto;
    private javax.swing.JButton botãoCheckIn;
    private javax.swing.JComboBox<String> comboBoxQuartos;
    private javax.swing.JComboBox<String> comboBoxReservas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxFuncionarios;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
