/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entidades.ServicoQuarto;
import exceção.ItemCadastradoException;
import exceção.ItemInexistenteException;
import fachada.Fachada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabi
 */
public class TelaAttRoomService extends javax.swing.JFrame {

    Fachada fachada;
    
    public TelaAttRoomService(Fachada fachada) {
        this.fachada = fachada;
        this.setTitle("Golden Hotel");
        initComponents();
        setSize(482,595);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entryCodigoAtual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entryPreco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imagem2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 404, 170);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Código:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 260, 80, 22);

        entryCodigoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCodigoAtualActionPerformed(evt);
            }
        });
        getContentPane().add(entryCodigoAtual);
        entryCodigoAtual.setBounds(170, 260, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Preço:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 300, 100, 22);

        entryPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(entryPreco);
        entryPreco.setBounds(170, 300, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 510, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 510, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, -30, 482, 595);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryCodigoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCodigoAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCodigoAtualActionPerformed

    private void entryPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryPrecoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo = entryCodigoAtual.getText();
        String p = entryPreco.getText();
        if(p.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            try{
                int c = Integer.parseInt(codigo);
                double preço = Double.parseDouble(p);
                ServicoQuarto s = fachada.buscarServico(c);
                fachada.atualizarOpcao(s, preço);
                JOptionPane.showMessageDialog(null, "Cadastrado Realizado!");
                this.dispose();
            }  catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Digite um preço válido!");
            } catch (ItemInexistenteException ex) {
                Logger.getLogger(TelaAttRoomService.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ItemCadastradoException ex) {
                Logger.getLogger(TelaAttRoomService.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entryCodigoAtual;
    private javax.swing.JTextField entryPreco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
